
---

> Math is not just a way of calculating numerical answers;
it is a way of thinking,
using clear definitions for concepts and rigorous logic
to organize our thoughts and back up our assertions.

@cheng2025math

---

These lecture notes use:

- mathematical notation
- algebra
- precalculus
- univariate calculus
- linear algebra
- vector calculus

Some key results are listed here.

# Notation {#sec-notation}

{{< include mds/_notation.qmd >}}

# Algebra {#sec-algebra}

{{< include mds/_algebra.qmd >}}

# Derivatives {#sec-derivatives}

{{< include mds/_calc-derivatives.qmd >}}

# Integration {#sec-integration}

{{< include mds/_calc-integrals.qmd >}}

# Double Integrals {#sec-double-integrals}

{{< include mds/_subfiles/_fubini_intro_thm.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_exm_fubini_nonrect.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_exm_fubini_fail.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_cor_fubini_rect.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_exm_fubini_rect.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_thm_fubini_tonelli.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_exm_fubini_fail_tonelli.qmd >}}

# Linear Algebra {#sec-linear-algebra}

{{< include mds/_subfiles/_sec_linear_algebra.qmd >}}

# Vector Calculus {#sec-vector-calculus}

{{< include mds/_subfiles/_sec_vector_calc.qmd >}}

# Additional resources

## Calculus 

- @mosaiccalc
- @khuri2003advanced
- @calclifesaver
- @larsonCalc11e
- @problifesavercalc
   - <http://www.youtube.com/watch?v=xYzQL0TUtBA>
   - <http://www.youtube.com/watch?v=Ps2SBo_WjoE>

## Linear Algebra and Vector Calculus

- @fieller2018basics
- @banerjee2014linear
- @searle2017matrix

## Numerical Analysis

- [Hua Zhou](https://hua-zhou.github.io/)'s [lecture notes for "UCLA Biostat 216 - Mathematical Methods for Biostatistics" (2023 Fall)](https://ucla-biostat-216.github.io/2023fall/schedule/schedule.html)

## Real Analysis

- @realanalysislifesaver

# References {.unnumbered}

::: {#refs}
:::
