---
title: "Calculus"
format:
  html: default
  revealjs:
    output-file: calculus-slides.html
  pdf:
    output-file: calculus-handout.pdf
  docx:
    output-file: calculus.docx
---

## Derivatives {#sec-derivatives}

{{< include latex-macros/macros.qmd >}}

{{< include mds/_calc-derivatives.qmd >}}

{{< slidebreak >}}

::: {.callout-tip title="Videos"}
Jon Krohn's "Calculus for Machine Learning" YouTube playlist has videos on limits, the idea behind derivatives, and the rules of differentiation:

- [Calculating Limits](https://www.youtube.com/watch?v=VUlOwf9P9Pc&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Exercises on Limits](https://www.youtube.com/watch?v=_2S3V5_DqAc&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Intro to Differential Calculus](https://www.youtube.com/watch?v=w1NJFmUEHWg&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [How Derivatives Arise from Limits](https://www.youtube.com/watch?v=9l0b37Kb030&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Derivative Notation](https://www.youtube.com/watch?v=457-HLoOo6U&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Derivative of a Constant](https://www.youtube.com/watch?v=GL5Rqgn7i9g&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Power Rule for Derivatives](https://www.youtube.com/watch?v=pyB2Rpcs6LQ&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Constant Multiple Rule for Derivatives](https://www.youtube.com/watch?v=zgNEiW0JHQA&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Sum Rule for Derivatives](https://www.youtube.com/watch?v=WgjuA94Dj54&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Exercises on Derivative Rules](https://www.youtube.com/watch?v=EANCBJiw9pE&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Product Rule for Derivatives](https://www.youtube.com/watch?v=-YFKJRp9Ncc&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Quotient Rule for Derivatives](https://www.youtube.com/watch?v=apqvDKiWMsQ&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Chain Rule for Derivatives](https://www.youtube.com/watch?v=zFOD3NR5I4Q&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Power Rule on a Function Chain](https://www.youtube.com/watch?v=JXG4g196cG0&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Advanced Exercises on Derivative Rules](https://www.youtube.com/watch?v=Qkyq95jYj9w&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
:::

## Integration {#sec-integration}

{{< include mds/_calc-integrals.qmd >}}

{{< slidebreak >}}

::: {.callout-tip title="Videos"}
Jon Krohn's "Calculus for Machine Learning" YouTube playlist has videos on integration:

- [Intro to Integral Calculus](https://www.youtube.com/watch?v=PNdKPsiaPhU&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Method of Exhaustion](https://www.youtube.com/watch?v=h0gPomI3h8o&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [What Integral Calculus Is](https://www.youtube.com/watch?v=O7TuAb_jHTs&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [The Integral Calculus Rules](https://www.youtube.com/watch?v=d-pyobAQ0iI&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Indefinite Integral Exercises](https://www.youtube.com/watch?v=PoTWa8X_EpI&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Definite Integrals](https://www.youtube.com/watch?v=lhtoBu51N7k&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Definite Integral Exercise](https://www.youtube.com/watch?v=kSZWX3j2u2U&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
- [Numeric Integration with Python](https://www.youtube.com/watch?v=f4nfLIkNv0A&list=PLRDl2inPrWQVu2OvnTvtkRpJ-wz-URMJx)
:::

## Double Integrals {#sec-double-integrals}

{{< include mds/_subfiles/_fubini_intro_thm.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_exm_fubini_nonrect.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_exm_fubini_fail.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_cor_fubini_rect.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_exm_fubini_rect.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_thm_fubini_tonelli.qmd >}}

{{< slidebreak >}}

{{< include mds/_subfiles/_exm_fubini_fail_tonelli.qmd >}}

## Additional resources {#sec-additional-resources}

- @mosaiccalc
- @khuri2003advanced
- @calclifesaver
- @larsonCalc11e
- @problifesavercalc
   - <http://www.youtube.com/watch?v=xYzQL0TUtBA>
   - <http://www.youtube.com/watch?v=Ps2SBo_WjoE>
- @realanalysislifesaver (the rigorous foundations behind these results)

## References {.unnumbered}

::: {#refs}
:::
